---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: curl
spec:
  replicas: 3
  selector:
    matchLabels:
      app: curl
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: curl
    spec:
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: topology.kubernetes.io/zone
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              app: curl
      containers:
        - name: curl
          image: docker.io/curlimages/curl:latest
          args:
            - sh
            - -c
            - 'while true; do curl -s -v nginx 2>&1 | grep X-Server-Hostname; sleep 1; done;'